exclude:
  - frontend/node_modules/
  - node_modules/
  - .git/
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
permalink: pretty

baseurl: ""
url: "https://merkuryyi.github.io"